[infNFe]

versao=4.00



[Identificacao]

cUF=13

cNF=43211590

natOp=VENDA PRODUCAO DO ESTAB.

indPag=0

Modelo=65

Serie=4

nNF=6

dhEmi=07/01/2025 12:04

dhSaiEnt=

tpNF=1

idDest=1

cMunFG=3554003

tpAmb=2

tpImp=4

tpemis=1

finNFe=1

indFinal=1

indPres=1

indIntermed=

procEmi=0

verProc=1.0.0.0

dhCont=

xJust=



;Reforma tributaria

cMunFGIBS=

;



[Emitente]

CNPJCPF=11222333000144

xNome=RAZAO SOCIAL DE TESTE

xFant=FANTASIA DE TESTE

IE=687222333118

IEST=

IM=2648800

CNAE=6201500

CRT=3

xLgr=Logradouro

nro=1

xCpl=Complemento

xBairro=Bairro

cMun=1302603

xMun=MANAUS

UF=AM

CEP=17250000

cPais=1058

xPais=BRASIL

Fone=22223333



;Destinatário não obrigatorio na NFCe

[Destinatario]

CNPJCPF=77888222000155

xNome=TESTE DE NOME

indIEDest=9

IE=

ISUF=

IM=

Email=

xLgr=Rua Coronel Aureliano de Camargo

nro=123

xCpl=

xBairro=Centro

cMun=3554003

xMun=Tatui

UF=SP

CEP=18270170

cPais=1058

xPais=BRASIL

Fone=1532599600



[Produto001]

nItem=1

infAdProd=InfAdProd: PED123; PED456;| Teste

cProd=123456

cEAN=7896523206646

cBarra=ABC123456

xProd=Camisa Polo ACBr

NCM=61051000

CEST=

indEscala=

CNPJFab=

cBenef=

EXTIPI=

CFOP=5101

uCom=UN

qCom=1

vUnCom=100

vProd=100

cEANTrib=7896523206646

cBarraTrib=ABC123456

uTrib=UN

qTrib=1

vUnTrib=100

vFrete=0

vSeg=0

vDesc=0

vOutro=0

IndTot=1

xPed=

nItemPed=

nFCI=

nRECOPI=

pDevol=0

vIPIDevol=0

vTotTrib=0



; Reforma tributaria

;(''=tieNenhum,1=tieSim,0=tieNao)

indBemMovelUsado=

vItem=

;





[ICMS001]

orig=0

CST=20

modBC=0

pRedBC=0

cBenefRBC=

vBC=100

pICMS=18

vICMS=18

vBCFCP=0

pFCP=0

vFCP=0

modBCST=0

pMVAST=0

pRedBCST=0

vBCST=0

pICMSST=0

vICMSST=0

vBCFCPST=100

pFCPST=2

vFCPST=2

UFST=

pBCOp=0

vBCSTRet=0

pST=0

vICMSSTRet=0

vBCFCPSTRet=0

pFCPSTRet=0

vFCPSTRet=0

motDesICMS=9

pCredSN=0

vCredICMSSN=0

vBCSTDest=0

vICMSSTDest=0

vICMSDeson=8

vICMSOp=0

pDif=0

vICMSDif=0

pRedBCEfet=0

vBCEfet=0

pICMSEfet=0

vICMSEfet=0

vICMSSubstituto=0

vICMSSTDeson=0

motDesICMSST=9

pFCPDif=0

vFCPDif=0

vFCPEfet=0

adRemICMS=0

vICMSMono=0

adRemICMSReten=0

vICMSMonoReten=0

vICMSMonoDif=0

adRemICMSRet=0

vICMSMonoRet=0

qBCMono=0

qBCMonoReten=0

pRedAdRem=0

motRedAdRem=1

qBCMonoRet=0

vICMSMonoOp=0



[ICMSUFDEST001]

vBCUFDest=0

vBCFCPUFDest=0

pICMSUFDest=0

pICMSInter=0

pICMSInterPart=0

vICMSUFDest=0

vICMSUFRemet=0

pFCPUFDest=0

vFCPUFDest=0



[PIS001]

CST=99

vBC=0

pPIS=0

qBCProd=0

vAliqProd=0

vPIS=0



[COFINS001]

CST=99

vBC=0

pCOFINS=0

qBCProd=0

vAliqProd=0

vCOFINS=0



;Reforma Tributaria

;Não informar o grupo "ISXXX" no momento. Ele entra em vigor apenas em 2027.

[IS001]

;deixar em branco ou usar cstis000

CSTIS=

;deixar em branco ou usar 000001

cClassTribIS=

vBCIS=

pIS=

pISEspec=

uTrib=

qTrib=

vIS=



[IBSCBS001]

;'','000', '010', '011', '200', '210', '220', '221', '222', '400', 

;'410', '510','550', '620', '800', '810', '820', '830'

CST=

cClassTrib=

;



; Reforma tributaria 

;gIBSCBS001, gIBSCBSMono001 e gTransfCred001  é um "Choice Group" no Layout, ou seja, apenas uma das seções deve constar no arquivo INI



; Reforma tributaria 

[gIBSCBS001] 

vBC=

vIBS=

[gIBSUF001]

pIBSUF=

vIBSUF=

pDif=

vDif=

vDevTrib=

pRedAliq=

pAliqEfet=

[gIBSMun001]

pIBSMun=

vIBSMun=

pDif=

vDif=

vDevTrib=

pRedAliq=

pAliqEfet=

[gCBS001]

pCBS=

vCBS=

pDif=

vDif=

vDevTrib=

pRedAliq=

pAliqEfet=

[gTribRegular001]

;'','000', '010', '011', '200', '210', '220', '221', '222', 

;'400', '410', '510','550', '620', '800', '810', '820', '830'

CSTReg=

cClassTribReg=

pAliqEfetRegIBSUF=

vTribRegIBSUF=

pAliqEfetRegIBSMun=

vTribRegIBSMun=

pAliqEfetRegCBS=

vTribRegCBS=

[gIBSCredPres001]

;'','01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12', '13';

cCredPres=

pCredPres=

vCredPres=

[gCBSCredPres001]

;'','01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12', '13';

cCredPres=

pCredPres=

vCredPres=

; Reforma tributaria 

[gTribCompraGov001] 

pAliqIBSUF=

vTribIBSUF=

pAliqIBSMun=

vTribIBSMun=

pAliqCBS=

vTribCBS=

;



; Reforma tributaria 

[gIBSCBSMono001]

vTotIBSMonoItem=

vTotCBSMonoItem=



[gMonoPadrao001]

qBCMono=

adRemIBS=

adRemCBS=

vIBSMono=

vCBSMono=



[gMonoReten001]

qBCMonoReten=

adRemIBSReten=

vIBSMonoReten=

adRemCBSReten=

vCBSMonoReten=



[gMonoRet001]

qBCMonoRet=

adRemIBSRet=

vIBSMonoRet=

adRemCBSRet=

vCBSMonoRet=



[gMonoDif001]

pDifIBS=

vIBSMonoDif=

pDifCBS=

vCBSMonoDif=

;



; Reforma tributaria

[gTransfCred001]

vIBS=

vCBS=

;



; Reforma tributaria 

[gCredPresIBSZFM001]

;'', '0','1', '2', '3', '4';

tpCredPresIBSZFM=

vCredPresIBSZFM=

;



[defensivo01]

nReceituario=

CPFRespTec=



[guiaTransito]

UFGuia=

tpGuia=

serieGuia=

nGuia=



[Total]

vBC=100

vICMS=18

vICMSDeson=8

vFCP=0

vICMSUFDest=0

vICMSUFRemet=0

vFCPUFDest=0

vBCST=0

vST=0

vFCPST=0

vFCPSTRet=0

qBCMono=0

vICMSMono=0

qBCMonoReten=0

vICMSMonoReten=0

qBCMonoRet=0

vICMSMonoRet=0

vProd=100

vFrete=0

vSeg=0

vDesc=0

vII=0

vIPI=0

vIPIDevol=0

vPIS=0

vCOFINS=0

vOutro=0

vNF=92

vTotTrib=0

;Reforma tributaria

vNFTot=

;

;Reforma tributaria

[ISTot]

vIS=

[IBSCBSTot]

vBCIBSCBS=

[gIBS]

vIBS=

vCredPres=

vCredPresCondSus=

[gIBSUFTot]

vDif=

vDevTrib=

vIBSUF=

[gIBSMunTot]

vDif=

vDevTrib=

vIBSMun=

[gCBSTot]

vDif=

vDevTrib=

vCBS=

vCredPres=

vCredPresCondSus=

[gMono]

vIBSMono=

vCBSMono=

vIBSMonoReten=

vCBSMonoReten=

vIBSMonoRet=

vCBSMonoRet=

;



[ISSQNtot]

vServ=0

vBC=0

vISS=0

vPIS=0

vCOFINS=0

dCompet=30/12/1899

vDeducao=0

vOutro=0

vDescIncond=0

vDescCond=0

vISSRet=0

cRegTrib=1



[retTrib]

vRetPIS=0

vRetCOFINS=0

vRetCSLL=0

vBCIRRF=0

vIRRF=0

vBCRetPrev=0

vRetPrev=0



[Transportador]

modFrete=9

CNPJCPF=

xNome=

IE=

xEnder=

xMun=

UF=

vServ=0

vBCRet=0

pICMSRet=0

vICMSRet=0

CFOP=

cMunFG=0

Placa=

UFPlaca=

RNTC=

vagao=

balsa=



[Volume001]

qVol=1

esp=Especie

marca=Marca

nVol=Numero

pesoL=100

pesoB=110



;[Fatura]

;nFat=1001

;vOrig=100

;vDesc=0

;vLiq=100

;

;[Duplicata001]

;nDup=001

;dVenc=24/08/2024

;vDup=50

;

;[Duplicata002]

;nDup=002

;dVenc=03/09/2024

;vDup=50



[pag001]

tPag=01

xPag=

vPag=46

dPag=30/12/1899

CNPJPag=

UFPag=

indPag=0

tpIntegra=

CNPJ=

tBand=

cAut=

CNPJReceb=

idTermPag=



[pag002]

tPag=03

xPag=

vPag=46

dPag=30/12/1899

CNPJPag=

UFPag=

indPag=0

tpIntegra=0

CNPJ=

tBand=

cAut=

CNPJReceb=

idTermPag=

vTroco=0



[infIntermed]

CNPJ=

idCadIntTran=



[DadosAdicionais]

infAdFisco=InfAdFisco: PED123; PED465; ;|

infCpl=infCpl: PED123; PED456; ;|



[InfAdic001]

xCampo=ObsCont-Ped132;|

xTexto=ObsCont-Texto; Text2; Texto3|



[ObsFisco001]

xCampo=ObsFisco-Ped123|

xTexto=ObsFisco-Texto; Texto2; Texto3;|





[infRespTec]

CNPJ=

xContato=

email=

fone=