CREATE TABLE IF NOT EXISTS invoice_items (
    id UUID PRIMARY KEY,
    invoice_id UUID NOT NULL REFERENCES invoices(id) ON DELETE CASCADE,
    n_item INT NOT NULL,
    c_prod VARCHAR(255) NOT NULL,
    c_ean VARCHAR(255) NOT NULL,
    x_prod VARCHAR(255) NOT NULL,
    ncm VARCHAR(8) NOT NULL,
    cest VARCHAR(10),
    cfop VARCHAR(4) NOT NULL,
    u_com VARCHAR(10) NOT NULL,
    q_com DECIMAL(15,4) NOT NULL,
    v_un_com DECIMAL(21,10) NOT NULL,
    v_prod DECIMAL(15,2) NOT NULL,
    c_ean_trib VARCHAR(255),
    u_trib VARCHAR(10),
    q_trib DECIMAL(15,4),
    v_un_trib DECIMAL(21,10),
    v_frete DECIMAL(15,2) NOT NULL DEFAULT 0,
    v_seg DECIMAL(15,2) NOT NULL DEFAULT 0,
    v_desc DECIMAL(15,2) NOT NULL DEFAULT 0,
    v_outro DECIMAL(15,2) NOT NULL DEFAULT 0,
    ind_tot SMALLINT NOT NULL,
    x_ped VARCHAR(50),
    n_item_ped VARCHAR(50),
    v_tot_trib DECIMAL(15,2),
    inf_ad_prod TEXT,
    ind_escala VARCHAR(50),
    cnpj_fab VARCHAR(14),
    c_benef VARCHAR(50),
    ind_bem_movel_usado SMALLINT,
    v_item DECIMAL(15,2),

    icms_orig SMALLINT,
    icms_cst VARCHAR(3),
    icms_csosn VARCHAR(4),
    icms_mod_bc SMALLINT,
    icms_p_red_bc DECIMAL(7,4),
    icms_v_bc DECIMAL(15,2),
    icms_p_icms DECIMAL(7,4),
    icms_v_icms DECIMAL(15,2),
    icms_mod_bc_st SMALLINT,
    icms_p_mva_st DECIMAL(7,4),
    icms_p_red_bc_st DECIMAL(7,4),
    icms_v_bc_st DECIMAL(15,2),
    icms_p_icms_st DECIMAL(7,4),
    icms_v_icms_st DECIMAL(15,2),
    icms_uf_st VARCHAR(2),
    icms_p_bc_op DECIMAL(7,4),
    icms_v_bc_st_ret DECIMAL(15,2),
    icms_v_icms_st_ret DECIMAL(15,2),
    icms_mot_des SMALLINT,
    icms_p_cred_sn DECIMAL(7,4),
    icms_v_cred_icms_sn DECIMAL(15,2),
    icms_v_icms_deson DECIMAL(15,2),
    icms_v_icms_op DECIMAL(15,2),
    icms_p_dif DECIMAL(7,4),
    icms_v_icms_dif DECIMAL(15,2),
    icms_p_st DECIMAL(7,4),
    icms_v_bc_fcp DECIMAL(15,2),
    icms_p_fcp DECIMAL(7,4),
    icms_v_fcp DECIMAL(15,2),
    icms_v_bc_fcp_st_ret DECIMAL(15,2),
    icms_p_fcp_st_ret DECIMAL(7,4),
    icms_v_fcp_st_ret DECIMAL(15,2),
    icms_p_red_bc_efet DECIMAL(7,4),
    icms_v_bc_efet DECIMAL(15,2),
    icms_p_icms_efet DECIMAL(7,4),
    icms_v_icms_efet DECIMAL(15,2),
    icms_v_icms_substituto DECIMAL(15,2),

    icms_q_bc_mono DECIMAL(15,4),
    icms_ad_rem_icms DECIMAL(7,4),
    icms_v_icms_mono DECIMAL(15,2),
    icms_q_bc_mono_reten DECIMAL(15,4),
    icms_ad_rem_icms_reten DECIMAL(7,4),
    icms_v_icms_mono_reten DECIMAL(15,2),
    icms_p_red_ad_rem DECIMAL(7,4),
    icms_mot_red_ad_rem SMALLINT,
    icms_q_bc_mono_ret DECIMAL(15,4),
    icms_v_icms_mono_op DECIMAL(15,2),
    icms_v_icms_mono_dif DECIMAL(15,2),
    icms_ad_rem_icms_ret DECIMAL(7,4),
    icms_v_icms_mono_ret DECIMAL(15,2),

    icms_uf_dest_v_bc DECIMAL(15,2),
    icms_uf_dest_v_bc_fcp DECIMAL(15,2),
    icms_uf_dest_p_fcp DECIMAL(7,4),
    icms_uf_dest_p_icms DECIMAL(7,4),
    icms_uf_dest_p_icms_inter DECIMAL(7,4),
    icms_uf_dest_p_icms_inter_part DECIMAL(7,4),
    icms_uf_dest_v_fcp DECIMAL(15,2),
    icms_uf_dest_v_icms DECIMAL(15,2),
    icms_uf_dest_v_icms_remet DECIMAL(15,2),

    pis_cst VARCHAR(3),
    pis_v_bc DECIMAL(15,2),
    pis_p_pis DECIMAL(7,4),
    pis_q_bc_prod DECIMAL(15,4),
    pis_v_aliq_prod DECIMAL(15,4),
    pis_v_pis DECIMAL(15,2),

    cofins_cst VARCHAR(3),
    cofins_v_bc DECIMAL(15,2),
    cofins_p_cofins DECIMAL(7,4),
    cofins_q_bc_prod DECIMAL(15,4),
    cofins_v_aliq_prod DECIMAL(15,4),
    cofins_v_cofins DECIMAL(15,2),

    ii_v_bc DECIMAL(15,2),
    ii_v_desp_adu DECIMAL(15,2),
    ii_v_ii DECIMAL(15,2),
    ii_v_iof DECIMAL(15,2),

    ipi_cst VARCHAR(3),
    ipi_c_enq VARCHAR(5),
    ipi_v_bc DECIMAL(15,2),
    ipi_p_ipi DECIMAL(7,4),
    ipi_v_ipi DECIMAL(15,2),

    is_cst VARCHAR(3),
    is_c_class_trib VARCHAR(10),
    is_v_bc DECIMAL(15,2),
    is_p_is DECIMAL(7,4),
    is_p_is_espec DECIMAL(7,4),
    is_v_is DECIMAL(15,2),

    ibs_cbs_cst VARCHAR(3),
    ibs_cbs_c_class_trib VARCHAR(10),
    ibs_cbs_v_bc DECIMAL(15,2),
    ibs_cbs_v_ibs DECIMAL(15,2),
    ibs_uf_p DECIMAL(7,4),
    ibs_uf_v DECIMAL(15,2),
    ibs_uf_p_dif DECIMAL(7,4),
    ibs_uf_v_dif DECIMAL(15,2),
    ibs_uf_v_dev_trib DECIMAL(15,2),
    ibs_uf_p_red_aliq DECIMAL(7,4),
    ibs_uf_p_aliq_efet DECIMAL(7,4),
    ibs_mun_p DECIMAL(7,4),
    ibs_mun_v DECIMAL(15,2),
    ibs_mun_p_dif DECIMAL(7,4),
    ibs_mun_v_dif DECIMAL(15,2),
    ibs_mun_v_dev_trib DECIMAL(15,2),
    ibs_mun_p_red_aliq DECIMAL(7,4),
    ibs_mun_p_aliq_efet DECIMAL(7,4),
    cbs_p DECIMAL(7,4),
    cbs_v DECIMAL(15,2),
    cbs_p_dif DECIMAL(7,4),
    cbs_v_dif DECIMAL(15,2),
    cbs_v_dev_trib DECIMAL(15,2),
    cbs_p_red_aliq DECIMAL(7,4),
    cbs_p_aliq_efet DECIMAL(7,4),

    trib_reg_cst VARCHAR(3),
    trib_reg_c_class_trib VARCHAR(10),
    trib_reg_p_aliq_ibs_uf DECIMAL(7,4),
    trib_reg_v_ibs_uf DECIMAL(15,2),
    trib_reg_p_aliq_ibs_mun DECIMAL(7,4),
    trib_reg_v_ibs_mun DECIMAL(15,2),
    trib_reg_p_aliq_cbs DECIMAL(7,4),
    trib_reg_v_cbs DECIMAL(15,2),

    ibs_cred_pres_cod VARCHAR(10),
    ibs_cred_pres_p DECIMAL(7,4),
    ibs_cred_pres_v DECIMAL(15,2),
    cbs_cred_pres_cod VARCHAR(10),
    cbs_cred_pres_p DECIMAL(7,4),
    cbs_cred_pres_v DECIMAL(15,2),

    gov_p_aliq_ibs_uf DECIMAL(7,4),
    gov_v_trib_ibs_uf DECIMAL(15,2),
    gov_p_aliq_ibs_mun DECIMAL(7,4),
    gov_v_trib_ibs_mun DECIMAL(15,2),
    gov_p_aliq_cbs DECIMAL(7,4),
    gov_v_trib_cbs DECIMAL(15,2),

    mono_v_tot_ibs DECIMAL(15,2),
    mono_v_tot_cbs DECIMAL(15,2),
    mono_pad_q_bc DECIMAL(15,4),
    mono_pad_ad_rem_ibs DECIMAL(7,4),
    mono_pad_ad_rem_cbs DECIMAL(7,4),
    mono_pad_v_ibs DECIMAL(15,2),
    mono_pad_v_cbs DECIMAL(15,2),
    mono_reten_q_bc DECIMAL(15,4),
    mono_reten_ad_rem_ibs DECIMAL(7,4),
    mono_reten_v_ibs DECIMAL(15,2),
    mono_reten_ad_rem_cbs DECIMAL(7,4),
    mono_reten_v_cbs DECIMAL(15,2),
    mono_ret_q_bc DECIMAL(15,4),
    mono_ret_ad_rem_ibs DECIMAL(7,4),
    mono_ret_v_ibs DECIMAL(15,2),
    mono_ret_ad_rem_cbs DECIMAL(7,4),
    mono_ret_v_cbs DECIMAL(15,2),
    mono_dif_p_ibs DECIMAL(7,4),
    mono_dif_v_ibs DECIMAL(15,2),
    mono_dif_p_cbs DECIMAL(7,4),
    mono_dif_v_cbs DECIMAL(15,2),

    transf_cred_v_ibs DECIMAL(15,2),
    transf_cred_v_cbs DECIMAL(15,2),
    cred_pres_ibs_zfm_tp VARCHAR(10),
    cred_pres_ibs_zfm_v DECIMAL(15,2)
);

CREATE INDEX idx_invoice_items_invoice_id ON invoice_items(invoice_id);
