package service

import (
	"bufio"
	"context"
	"fmt"
	"log/slog"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"

	"github.com/AdelmoMJunior/GoACBr/internal/acbr"
	"github.com/AdelmoMJunior/GoACBr/internal/crypto"
	"github.com/AdelmoMJunior/GoACBr/internal/repository"
)

// ufToIBGECode maps Brazilian state abbreviations to IBGE numeric codes.
var ufToIBGECode = map[string]int{
	"AC": 12, "AL": 27, "AM": 13, "AP": 16, "BA": 29,
	"CE": 23, "DF": 53, "ES": 32, "GO": 52, "MA": 21,
	"MG": 31, "MS": 50, "MT": 51, "PA": 15, "PB": 25,
	"PE": 26, "PI": 22, "PR": 41, "RJ": 33, "RN": 24,
	"RO": 11, "RR": 14, "RS": 43, "SC": 42, "SE": 28,
	"SP": 35, "TO": 17,
}

// UFToCode converts a UF abbreviation (e.g. "SP") to the IBGE numeric code (35).
func UFToCode(uf string) int {
	if code, ok := ufToIBGECode[strings.ToUpper(uf)]; ok {
		return code
	}
	return 91
}

// configureHandleForCompany fetches real company/cert data from DB and
// configures the ACBr handle using the "generate defaults then patch" approach:
//  1. ConfigGravar — let ACBr dump a valid INI with all default values
//  2. Patch only the fields we need (cert, UF, ambiente, paths)
//  3. ConfigLer — reload the patched INI
func configureHandleForCompany(
	ctx context.Context,
	hd *acbr.Handle,
	pool *acbr.HandlePool,
	companyID uuid.UUID,
	compRepo repository.CompanyRepository,
	certRepo repository.CertificateRepository,
	cryptoSvc crypto.Service,
) error {
	// 1. Fetch company data
	comp, err := compRepo.GetByID(ctx, companyID)
	if err != nil {
		return fmt.Errorf("failed to fetch company %s: %w", companyID, err)
	}

	// 2. Fetch certificate
	cert, err := certRepo.GetByCompanyID(ctx, companyID)
	if err != nil {
		return fmt.Errorf("company %s has no certificate: %w", companyID, err)
	}

	// 3. Decrypt PFX password
	passBytes, err := cryptoSvc.Decrypt(cert.PFXPasswordEnc)
	if err != nil {
		return fmt.Errorf("failed to decrypt certificate password: %w", err)
	}
	pfxPassword := string(passBytes)

	// 4. Decrypt PFX data and write to temp file
	pfxBytes, err := cryptoSvc.Decrypt(string(cert.PFXData))
	if err != nil {
		return fmt.Errorf("failed to decrypt certificate PFX: %w", err)
	}

	certsDir := "/tmp/acbr_certs"
	os.MkdirAll(certsDir, 0700)
	pfxPath := filepath.Join(certsDir, companyID.String()+".pfx")
	if err := os.WriteFile(pfxPath, pfxBytes, 0600); err != nil {
		return fmt.Errorf("failed to write PFX to temp file: %w", err)
	}

	slog.Info("Configuring ACBr handle for company",
		"company_id", companyID,
		"cnpj", comp.CNPJ,
		"uf", comp.UF,
		"ambiente", comp.Ambiente,
	)

	// 5. Let ACBr generate the default INI (all fields with valid defaults)
	iniDir := "/tmp/acbr_ini"
	os.MkdirAll(iniDir, 0700)
	iniPath := filepath.Join(iniDir, companyID.String()+".ini")

	if err := hd.ConfigGravar(iniPath); err != nil {
		slog.Error("ConfigGravar failed", "path", iniPath, "error", err)
		return fmt.Errorf("failed to generate default ACBr config: %w", err)
	}
	slog.Debug("Default INI generated by ACBr", "path", iniPath)

	// 6. Read the generated INI and patch company-specific values
	schemasPath := pool.SchemasPath
	if schemasPath == "" {
		schemasPath = "/app/data/Schemas/NFe"
	}
	logPath := pool.LogPath
	if logPath == "" {
		logPath = "/tmp/acbr_logs"
	}
	os.MkdirAll(logPath, 0755)

	savePath := "/tmp/acbr_nfe/" + companyID.String() + "/"
	pdfPath := "/tmp/acbr_pdf/" + companyID.String() + "/"
	os.MkdirAll(savePath, 0755)
	os.MkdirAll(pdfPath, 0755)

	ambiente := strconv.Itoa(int(comp.Ambiente))
	if comp.Ambiente == 0 {
		ambiente = "2"
	}

	// Map of section -> key -> value to patch
	patches := map[string]map[string]string{
		"Principal": {
			"TipoResposta": "2",
			"LogNivel":     "3",
			"LogPath":      logPath,
		},
		"DFe": {
			"SSLLib":     "1",
			"CryptLib":   "1",
			"HttpLib":    "3",
			"XmlSignLib": "4",
			"ArquivoPFX": pfxPath,
			"Senha":      pfxPassword,
		},
		"NFe": {
			"ModeloDF":  "55",
			"VersaoDF":  "4.00",
			"SalvarXML": "1",
		},
		"WebService": {
			"UF":       comp.UF,
			"Ambiente": ambiente,
		},
		"Arquivos": {
			"Salvar":      "1",
			"PathSalvar":  savePath,
			"PathSchemas": schemasPath,
		},
		"DANFE": {
			"PathPDF": pdfPath,
		},
	}

	if err := patchINIFile(iniPath, patches); err != nil {
		slog.Error("Failed to patch INI file", "path", iniPath, "error", err)
		return fmt.Errorf("failed to patch ACBr config: %w", err)
	}
	slog.Debug("INI patched with company config", "path", iniPath)

	// 7. Reload the patched INI
	if err := hd.ConfigLer(iniPath); err != nil {
		slog.Error("ConfigLer failed after patching", "path", iniPath, "error", err)
		return fmt.Errorf("failed to reload ACBr config: %w", err)
	}

	hd.ConfiguredFor = companyID
	slog.Info("ACBr handle configured successfully", "company_id", companyID)
	return nil
}

// patchINIFile reads an INI file, patches specific section/key values,
// and writes it back. Keys not present in the file are appended to their section.
func patchINIFile(path string, patches map[string]map[string]string) error {
	data, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("failed to read INI: %w", err)
	}

	lines := strings.Split(string(data), "\n")
	currentSection := ""
	applied := make(map[string]map[string]bool) // track which patches were applied

	for i, line := range lines {
		trimmed := strings.TrimSpace(line)

		// Detect section headers
		if strings.HasPrefix(trimmed, "[") && strings.HasSuffix(trimmed, "]") {
			// Before leaving the current section, append any unapplied patches
			if currentSection != "" {
				if sectionPatches, ok := patches[currentSection]; ok {
					for key, val := range sectionPatches {
						if applied[currentSection] == nil || !applied[currentSection][key] {
							lines[i] = key + "=" + val + "\n" + lines[i]
							if applied[currentSection] == nil {
								applied[currentSection] = make(map[string]bool)
							}
							applied[currentSection][key] = true
						}
					}
				}
			}
			currentSection = strings.Trim(trimmed, "[]")
			continue
		}

		// Check if this line is a key=value in a patched section
		if currentSection == "" {
			continue
		}
		sectionPatches, hasSectionPatches := patches[currentSection]
		if !hasSectionPatches {
			continue
		}

		eqIdx := strings.Index(trimmed, "=")
		if eqIdx < 0 {
			continue
		}

		key := strings.TrimSpace(trimmed[:eqIdx])
		if newVal, needsPatch := sectionPatches[key]; needsPatch {
			lines[i] = key + "=" + newVal
			if applied[currentSection] == nil {
				applied[currentSection] = make(map[string]bool)
			}
			applied[currentSection][key] = true
		}
	}

	// Append any remaining unapplied patches for the last section
	if currentSection != "" {
		if sectionPatches, ok := patches[currentSection]; ok {
			for key, val := range sectionPatches {
				if applied[currentSection] == nil || !applied[currentSection][key] {
					lines = append(lines, key+"="+val)
				}
			}
		}
	}

	// Append entirely new sections that didn't exist in the original file
	for section, sectionPatches := range patches {
		if applied[section] == nil || len(applied[section]) == 0 {
			// Check if section existed at all
			sectionExists := false
			for _, l := range lines {
				if strings.TrimSpace(l) == "["+section+"]" {
					sectionExists = true
					break
				}
			}
			if !sectionExists {
				lines = append(lines, "\n["+section+"]")
				for key, val := range sectionPatches {
					lines = append(lines, key+"="+val)
				}
			}
		}
	}

	output := strings.Join(lines, "\n")
	return os.WriteFile(path, []byte(output), 0600)
}

// extractFromINI helper to extract fields from ACBr INI response.
func extractFromINI(content, section, key string) string {
	scanner := bufio.NewScanner(strings.NewReader(content))
	prefix := key + "="
	inSection := section == ""

	for scanner.Scan() {
		l := strings.TrimSpace(scanner.Text())
		if l == "" {
			continue
		}

		if strings.HasPrefix(l, "[") && strings.HasSuffix(l, "]") {
			currSection := strings.Trim(l, "[]")
			if section != "" {
				inSection = strings.EqualFold(currSection, section)
			}
			continue
		}

		if inSection && strings.HasPrefix(l, prefix) {
			return strings.TrimPrefix(l, prefix)
		}
	}
	return "UNKNOWN"
}

func parseINIInt(s string) int {
	var v int
	fmt.Sscanf(s, "%d", &v)
	return v
}

func parseINIDecimal(s string) decimal.Decimal {
	s = strings.Replace(s, ",", ".", -1)
	d, _ := decimal.NewFromString(s)
	return d
}

func parseINITime(s string) time.Time {
	formats := []string{
		"2006-01-02T15:04:05-07:00",
		"02/01/2006 15:04:05",
		"2006-01-02T15:04:05",
	}
	for _, f := range formats {
		t, err := time.Parse(f, s)
		if err == nil {
			return t
		}
	}
	return time.Now()
}

func getSections(content string) []string {
	var sections []string
	scanner := bufio.NewScanner(strings.NewReader(content))
	for scanner.Scan() {
		l := strings.TrimSpace(scanner.Text())
		if strings.HasPrefix(l, "[") && strings.HasSuffix(l, "]") {
			sections = append(sections, strings.Trim(l, "[]"))
		}
	}
	return sections
}
