CREATE TABLE IF NOT EXISTS invoices (
    id UUID PRIMARY KEY,
    company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
    chave VARCHAR(44) NOT NULL UNIQUE,
    c_nf VARCHAR(8) NOT NULL,
    nat_op VARCHAR(255) NOT NULL,
    modelo SMALLINT NOT NULL,
    serie INT NOT NULL,
    numero INT NOT NULL,
    dh_emissao TIMESTAMPTZ NOT NULL,
    dh_sai_ent TIMESTAMPTZ,
    tp_nf SMALLINT NOT NULL,
    id_dest SMALLINT NOT NULL,
    c_mun_fg VARCHAR(7) NOT NULL,
    tp_imp SMALLINT NOT NULL,
    tp_emis SMALLINT NOT NULL,
    tp_amb SMALLINT NOT NULL,
    fin_nfe SMALLINT NOT NULL,
    ind_final SMALLINT NOT NULL,
    ind_pres SMALLINT NOT NULL,
    proc_emi SMALLINT NOT NULL,
    ver_proc VARCHAR(50) NOT NULL,
    ind_intermed VARCHAR(10),
    c_mun_fg_ibs VARCHAR(7),
    tp_nf_debito VARCHAR(2),
    tp_nf_credito VARCHAR(2),
    tp_ente_gov SMALLINT,
    p_redutor DECIMAL(7,4),
    tp_oper_gov SMALLINT,
    
    dest_cnpj_cpf VARCHAR(14),
    dest_nome VARCHAR(255),
    dest_ie VARCHAR(50),
    dest_ind_ie_dest SMALLINT,
    dest_email VARCHAR(255),
    dest_logradouro VARCHAR(255),
    dest_numero VARCHAR(50),
    dest_complemento VARCHAR(255),
    dest_bairro VARCHAR(255),
    dest_cod_municipio VARCHAR(7),
    dest_municipio VARCHAR(255),
    dest_uf VARCHAR(2),
    dest_cep VARCHAR(8),
    
    tot_v_bc DECIMAL(15,2) NOT NULL DEFAULT 0,
    tot_v_icms DECIMAL(15,2) NOT NULL DEFAULT 0,
    tot_v_icms_deson DECIMAL(15,2) NOT NULL DEFAULT 0,
    tot_v_fcp DECIMAL(15,2) NOT NULL DEFAULT 0,
    tot_v_bc_st DECIMAL(15,2) NOT NULL DEFAULT 0,
    tot_v_st DECIMAL(15,2) NOT NULL DEFAULT 0,
    tot_v_fcp_st DECIMAL(15,2) NOT NULL DEFAULT 0,
    tot_v_prod DECIMAL(15,2) NOT NULL DEFAULT 0,
    tot_v_frete DECIMAL(15,2) NOT NULL DEFAULT 0,
    tot_v_seg DECIMAL(15,2) NOT NULL DEFAULT 0,
    tot_v_desc DECIMAL(15,2) NOT NULL DEFAULT 0,
    tot_v_ii DECIMAL(15,2) NOT NULL DEFAULT 0,
    tot_v_ipi DECIMAL(15,2) NOT NULL DEFAULT 0,
    tot_v_pis DECIMAL(15,2) NOT NULL DEFAULT 0,
    tot_v_cofins DECIMAL(15,2) NOT NULL DEFAULT 0,
    tot_v_outro DECIMAL(15,2) NOT NULL DEFAULT 0,
    tot_v_nf DECIMAL(15,2) NOT NULL DEFAULT 0,
    tot_v_tot_trib DECIMAL(15,2) NOT NULL DEFAULT 0,
    tot_v_ipi_devol DECIMAL(15,2) NOT NULL DEFAULT 0,
    tot_v_fcp_st_ret DECIMAL(15,2) NOT NULL DEFAULT 0,
    
    tot_q_bc_mono DECIMAL(15,4),
    tot_v_icms_mono DECIMAL(15,2),
    tot_q_bc_mono_reten DECIMAL(15,4),
    tot_v_icms_mono_reten DECIMAL(15,2),
    tot_q_bc_mono_ret DECIMAL(15,4),
    tot_v_icms_mono_ret DECIMAL(15,2),
    
    tot_v_nf_tot DECIMAL(15,2),
    tot_is_v_is DECIMAL(15,2),
    tot_ibs_cbs_v_bc DECIMAL(15,2),
    tot_ibs_v_ibs DECIMAL(15,2),
    tot_ibs_v_cred_pres DECIMAL(15,2),
    tot_ibs_v_cred_pres_cond_sus DECIMAL(15,2),
    tot_ibs_uf_v_dif DECIMAL(15,2),
    tot_ibs_uf_v_dev_trib DECIMAL(15,2),
    tot_ibs_uf_v_ibs_uf DECIMAL(15,2),
    tot_ibs_mun_v_dif DECIMAL(15,2),
    tot_ibs_mun_v_dev_trib DECIMAL(15,2),
    tot_ibs_mun_v_ibs_mun DECIMAL(15,2),
    tot_cbs_v_dif DECIMAL(15,2),
    tot_cbs_v_dev_trib DECIMAL(15,2),
    tot_cbs_v_cbs DECIMAL(15,2),
    tot_cbs_v_cred_pres DECIMAL(15,2),
    tot_cbs_v_cred_pres_cond_sus DECIMAL(15,2),
    tot_mono_v_ibs_mono DECIMAL(15,2),
    tot_mono_v_cbs_mono DECIMAL(15,2),
    tot_mono_v_ibs_mono_reten DECIMAL(15,2),
    tot_mono_v_cbs_mono_reten DECIMAL(15,2),
    tot_mono_v_ibs_mono_ret DECIMAL(15,2),
    tot_mono_v_cbs_mono_ret DECIMAL(15,2),
    
    protocolo VARCHAR(255),
    dh_recebimento TIMESTAMPTZ,
    status VARCHAR(50) NOT NULL,
    inf_ad_fisco TEXT,
    inf_cpl TEXT,
    xml_b2_key VARCHAR(500),
    pdf_b2_key VARCHAR(500),
    
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_invoices_company_id ON invoices(company_id);
CREATE INDEX idx_invoices_chave ON invoices(chave);
CREATE INDEX idx_invoices_dh_emissao ON invoices(dh_emissao);
